export * from './categories/Categories'
export * from './categories/Categories.module.scss'
export * from './pizza-block/PizzaBlock'
export * from './pizza-block/PizzaBlock.module.scss'
export * from '@/common/components/sortPopup/SortPopup'
export * from '@/common/components/sortPopup/SortPopup.module.scss'
